package aplicacion.modelo.dominio;
// Generated 12/06/2017 23:12:43 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.Usuario;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agente generated by hbm2java
 */
public class Agente  implements java.io.Serializable {


     private int legajo;
     private Usuario usuarios;
     private String apellido;
     private String apellidoCasada;
     private BigDecimal numeroDocumento;
     private String tipoDoc;
     private Date fechaNac;
     private String nroMatricula;
     private char sexo;
     private String estadoCivil;
     private String ocupacion;
     private String titulo;
     private String calle;
     private int numCalle;
     private String barrio;
     private String localidad;
     private String provincia;
     private int codPostal;
     private String mail;
     private boolean estado;
     private int telefono;
     private String tipoIdentificadorLaboral;
     private BigDecimal numIdentificador;
     private String nombre;
     private Set cargosDeclaradoses = new HashSet(0);

    public Agente() {
    }

	
   
    public Agente(int legajo, Usuario usuarios, String apellido, String apellidoCasada, BigDecimal numeroDocumento, String tipoDoc, Date fechaNac, String nroMatricula, char sexo, String estadoCivil, String ocupacion, String titulo, String calle, int numCalle, String barrio, String localidad, String provincia, int codPostal, String mail, boolean estado, int telefono, String tipoIdentificadorLaboral, BigDecimal numIdentificador, String nombre, Set cargosDeclaradoses) {
       this.legajo = legajo;
       this.usuarios = usuarios;
       this.apellido = apellido;
       this.apellidoCasada = apellidoCasada;
       this.numeroDocumento = numeroDocumento;
       this.tipoDoc = tipoDoc;
       this.fechaNac = fechaNac;
       this.nroMatricula = nroMatricula;
       this.sexo = sexo;
       this.estadoCivil = estadoCivil;
       this.ocupacion = ocupacion;
       this.titulo = titulo;
       this.calle = calle;
       this.numCalle = numCalle;
       this.barrio = barrio;
       this.localidad = localidad;
       this.provincia = provincia;
       this.codPostal = codPostal;
       this.mail = mail;
       this.estado = estado;
       this.telefono = telefono;
       this.tipoIdentificadorLaboral = tipoIdentificadorLaboral;
       this.numIdentificador = numIdentificador;
       this.nombre = nombre;
       this.cargosDeclaradoses = cargosDeclaradoses;
    }
   
    public int getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(int legajo) {
        this.legajo = legajo;
    }
    public Usuario getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuario usuarios) {
        this.usuarios = usuarios;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getApellidoCasada() {
        return this.apellidoCasada;
    }
    
    public void setApellidoCasada(String apellidoCasada) {
        this.apellidoCasada = apellidoCasada;
    }
    public BigDecimal getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(BigDecimal numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getNroMatricula() {
        return this.nroMatricula;
    }
    
    public void setNroMatricula(String nroMatricula) {
        this.nroMatricula = nroMatricula;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumCalle() {
        return this.numCalle;
    }
    
    public void setNumCalle(int numCalle) {
        this.numCalle = numCalle;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public int getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(int codPostal) {
        this.codPostal = codPostal;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getTipoIdentificadorLaboral() {
        return this.tipoIdentificadorLaboral;
    }
    
    public void setTipoIdentificadorLaboral(String tipoIdentificadorLaboral) {
        this.tipoIdentificadorLaboral = tipoIdentificadorLaboral;
    }
    public BigDecimal getNumIdentificador() {
        return this.numIdentificador;
    }
    
    public void setNumIdentificador(BigDecimal numIdentificador) {
        this.numIdentificador = numIdentificador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCargosDeclaradoses() {
        return this.cargosDeclaradoses;
    }
    
    public void setCargosDeclaradoses(Set cargosDeclaradoses) {
        this.cargosDeclaradoses = cargosDeclaradoses;
    }




}


