package aplicacion.modelo.dominio;
// Generated 12/06/2017 23:12:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcion generated by hbm2java
 */
public class Funcion  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private int cargaHoraria;
     private Set cargosDeclaradoses = new HashSet(0);

    public Funcion() {
    }

	
    public Funcion(int codigo, String nombre, int cargaHoraria) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.cargaHoraria = cargaHoraria;
    }
    public Funcion(int codigo, String nombre, int cargaHoraria, Set cargosDeclaradoses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.cargaHoraria = cargaHoraria;
       this.cargosDeclaradoses = cargosDeclaradoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(int cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public Set getCargosDeclaradoses() {
        return this.cargosDeclaradoses;
    }
    
    public void setCargosDeclaradoses(Set cargosDeclaradoses) {
        this.cargosDeclaradoses = cargosDeclaradoses;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 29 * hash + this.codigo;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Funcion other = (Funcion) obj;
        if (this.codigo != other.codigo) {
            return false;
        }
        return true;
    }
    
      
    

   

    @Override
    public String toString() {
        return String.format("Funcion[%d,%s]",codigo,nombre);
    }

   


}


