package aplicacion.modelo.dominio;
// Generated 12/06/2017 23:12:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nombre;
     private String password;
     private Set agenteses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String password) {
        this.nombre = nombre;
        this.password = password;
    }
    public Usuario(String nombre, String password, Set agenteses) {
       this.nombre = nombre;
       this.password = password;
       this.agenteses = agenteses;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getAgenteses() {
        return this.agenteses;
    }
    
    public void setAgenteses(Set agenteses) {
        this.agenteses = agenteses;
    }




}


